Repository SAP/ui5-webcomponents-ngx, pull requests merged in 2023-01, with the labels that each got.

#5 fix: added dependency on build for sync targets
  nx.json
Labels: bug, enhancement

#6 feat: introduced lerna
  lerna.json
  package.json
  yarn.lock
Labels: enhancement

#7 chore(ci): add greetings action
  .github/workflows/greetings.yml
Labels: tooling

#8 chore(commit): add github templates
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: tooling

#10 fix: fixed problems with executor resolution in yarn workspaces
  libs/webcomponents-nx/src/executors/sync/executor.js
Labels: bug, tooling
